baseurl = "/"
languageCode = "en-us"
title = "jar000ny"
theme = "hugo-theme-nix"

[params]
  GithubID = "jarooony"
  TwitterID = "your_twitter"
  LinkedInID = "your_linkedin"
  GoogleplusID = "your_googleplus"
  FacebookID = "your_facebook"
  Name = "Jar000ny"
  HeaderUsername = "jar000ny"
  HeaderHostname = "jarvis"
  Email = "your_email"
  About = "curiosity killed the cat"
  ProfilePicture = "https://yt3.ggpht.com/-Ad_vU57Cm24/AAAAAAAAAAI/AAAAAAAAAAA/kQR5aLZUtfg/s288-mo-c-c0xffffffff-rj-k-no/photo.jpg"
  GoogleAnalytics = "your_google_analytics_id"

[menu]
  [[menu.header]]
    name = "posts"
    weight = 0
    url = "/post"
  [[menu.header]]
    name = "links"
    weight = 1
    url = "/links"
